### ISSUE TITLE
Not working in brave browser

### ISSUE THREAD

**Issue by micsthepick** [rain-fighters/AudioPick#42]
Tested with latest version of brave browser (chromium based) and with youtube and twitch, windows 10 1909
Selecting any output device has no effect, only plays through default device.

**Comment by dmitrychepel** [comment]
have the same issue

**Comment by micsthepick** [comment]
@dmitrychepel 
it works fine in chrome for me, so it looks like you probably should open your own issue. I imagine this one will be closed (if it ever gets responded to) because this extension relies on some chrome (google) specific thing, but your issue is with chrome itself.

**Comment by dmitrychepel** [comment]
@micsthepick 
do you want to close it? if yes i will recreate issue.

**Comment by micsthepick** [comment]
@dmitrychepel I am not sure if this issue needs to be closed yet, I was redicting that it might, but you should still create a different issue, since your issue is specifically chrome, but my issue is specifically brave, and I am able to get chrome working fine

**Comment by saDimpartuSuseR** [comment]
This was working fine for me till I decided to reinstall Brave. Following the Microphone tip, this started working again although in a different manner. Clicking on the lock on the address bar and going into site settings and changing microphone and sound settings to Allow, then restarting the browser solved it. But in order to switch between devices, apparently I just have 2 options now, the Speaker and the Default System Device. I use virtual cable to route audio to OBS so the default system device is for some reason set to it, while the speaker plays the audio in my headphones xD. None of the other options work, the only way to change between the two is to choose either the Speaker or the Default.
![image](https://user-images.githubusercontent.com/67916183/94648675-a525a580-0310-11eb-9194-2b22687e9c55.png)

**Comment by micsthepick** [comment]
it's working strange for me too, the device list seems to be out of order, I'll select one device, and it goes to a completely different one

**Comment by tomocrafter** [comment]
I'm getting same problem, Seems like it is failed at dom change (setSinkId). It will always throws DOMException which is thrown when cannnot use audio device.

**Comment by micsthepick** [comment]
I looked through the list of forks, and there seems to be one that gets this extension to work again, but it still has the out of order issue: https://github.com/parazite13/AudioPick

**Comment by Fritomaster** [comment]
still broken latest updates for both.

**Comment by Vodianoi** [comment]
It seems to be pretty random, selecting device is not sync with popup. Sometimes changing device actually change the selected device (not the good one but changing anyway), and other times it's keeping the same.
It's working fine on Chrome, but on Brave, the devices seems to be selected randomly and popup is not sync. 
Maybe something's unauthorized ?

**Comment by ailispaw** [comment]
Hi, I realized that IDs of devices and their order are different between the page’s context and extension’s context.
That's why it doesn't work or just a few devices do sometimes.
I revised the code to use a device label instead of its order number.
Hope it will work for you, too.
https://github.com/ailispaw/AudioPick/tree/brave

**Comment by itsmeboy0** [comment]
A more recent extension that is available on the Chrome Store is working for me: https://github.com/ish-/AuRo
