### ISSUE TITLE
Selecting a different audio device has no effect (Chrome)

### ISSUE THREAD

**Issue by marstj** [rain-fighters/AudioPick#44]
I installed the plugin, restarted Chrome, went to youtube.com, and opened the AudioPick menu. I see all the audio devices I expect in it, with "System Default Device" selected.

When I try to select some other device, nothing happen and the next time I open the menu "System Default Device" is still selected.

- Tried both with and without setting the "Microphone" permission to "Allow" (I do hope it's possible to get it to work without that permission, because I'm not comfortable setting it on most sites).
- Tried with "Sound" permission set to both "Allow" and "Automatic (default)".
- Tried with and without a playing video during the change.

System: Chrome 85.0.4183.83, Linux

Thanks!

[Not sure there isn't a bug report for this already; it's hard to tell from their generally nondescript titles.]

**Comment by Zhyrclew** [comment]
I'm sorry that the microphone permission trick didn't work for you.
I suspect that your problem is elsewhere because the selected output device isn't kept selected after you close the menu.
As I understand it, in windows, it's the OS that 'graciously' look at the recommended audio output that chrome (or this extension) chose, and obeys it, discarding the chrome default audio output from the OS. It wouldn't surprise me that this wouldn't go as smoothly on Linux.

Sorry again but as it is, it's not possible to make the extension work without giving the website microphone permission, as it is explained in multiple places, like the website : 
> Note that the API requires a successful call to getUserMedia() for every site with audio sinks that need to be manipulated which - as a result - creates entries under contentSettings['microphone'], i. e. it allows those sites to access your microphone.

It's just that you should not have to do it manually, the extension knew how to automatically allow microphone access before a chrome update broke it.
Sorry I couldn't help more.

**Comment by alphonset69** [comment]
I would appreciate any other workarounds that anyone has figured out for this issue.  Nothing is working for me.

**Comment by TheFleshi** [comment]
You must set it to “On Click,” which will disable permissions until you click the icon in the menu bar.
That's how it worked for me.

**Comment by FatRomanticSlob** [comment]
> You must set it to “On Click,” which will disable permissions until you click the icon in the menu bar.
> That's how it worked for me.

Hmm. I'm having the same issue and setting the On Click didn't fix it for me. Let me restart...

**Comment by LexShadow** [comment]
I am also having this same issue On Click is enabled

**Comment by lrq3000** [comment]
If you enable microphone permissions for the site + activation on click, then it works flawlessly. I'm using it with a bluetooth paired speaker, works great!

To enable the microphone permission for the site you want, click on the little lock on the left of the URL bar, and click the "Parameters" button. Then search for the microphone entry and set "Allow" instead of "Ask".

Thanks a lot for the plugin @necropola ! Wonderful job!

**Comment by Dr4inder** [comment]
Doesnt work for me in chrome version 88
if i select the system default device i hear nothing, if i select any other device i hear sound via my system default device...

**Comment by veiico** [comment]
> If you enable microphone permissions for the site + activation on click, then it works flawlessly. I'm using it with a bluetooth paired speaker, works great!
> 
> To enable the microphone permission for the site you want, click on the little lock on the left of the URL bar, and click the "Parameters" button. Then search for the microphone entry and set "Allow" instead of "Ask".
> 
> Thanks a lot for the plugin @necropola ! Wonderful job!

This right here finally worked, opened new chrome session, did this and after refresh and audio source select it finally worked! Thanks for the solution! ❤️

**Comment by lrq3000** [comment]
Yes i use the plugin daily now since months, it works as long at microphone
permissions are given for the current website you visit. You can enable
microphone permissions for all websites making this plugin work on all
internet but it would be unsafe as then websites can record your sound
without you knowing. Hence permission on click is the best as it allows to
only give permission to websites you deem safe.

**Comment by KyleGuay** [comment]
I was able to resolve this issue by: 
1. Ensuring the AudioPick's site access permissions are set to "on all sites".
2. Then click the lock next to the website's URL and change microphone access to allow.

If after doing all of this, the extension still is not working properly:

3. Check your operating system's advanced sound options and make sure Google Chrome's output device is set to default.

It seems, if you have Google Chrome assigned to a specific device via windows, the OS will overwrite it and still play audio through the OS assigned device.

I hope this helps anyone having issues with this extension.

**Comment by cordovas231** [comment]
For everyone who is still having a similar issue despite enabling mic permissions, it could be due to other extensions. I had to disable HTTPS Everywhere to get AudioPick to work.

**Comment by ish-** [comment]
@cordovas231 @marstj 
You could try this extension: https://chrome.google.com/webstore/detail/auro-audio-output-device/hglnindfakmbhhkldompfjeknfapaceh?hl=ru&authuser=0
It works for every tab exclusively.
If you'll have any wishes, just leave an issue on github =)

**Comment by PixeldroidOF** [comment]
> If you enable microphone permissions for the site + activation on click, then it works flawlessly. I'm using it with a bluetooth paired speaker, works great!
> 
> To enable the microphone permission for the site you want, click on the little lock on the left of the URL bar, and click the "Parameters" button. Then search for the microphone entry and set "Allow" instead of "Ask".
> 
> Thanks a lot for the plugin @necropola ! Wonderful job!

This one works. I've tried using the latest commit @8008f271e7cb3713290d73ea483df96a04745c06 but it's just the same.

**Comment by XanSama** [comment]
Can also checkout issue #47 . Fixes the problems and has browser defaults + per domain defaults.
