### ISSUE TITLE
The Spotify Web Playback SDK isn't supported

### ISSUE THREAD

**Issue by fastnlight0** [rain-fighters/AudioPick#52]
Websites that implement the Spotify Web Playback SDK (eg. [spotify.sinno.link](https://spotify.sinno.link) (my site)) don't seem to work with this extension. Could this be added?

**Comment by necropola** [comment]
- Why does your site immediiately ask for spotify authentication?
- Does your site use iframes to embed the spoitify player? If so,  it will not work any time soon, due to cross-domain restrictions of the Media Stream API.

**Comment by fastnlight0** [comment]
1: The Web Playback SDK requires users to log in with Spotify. 

2: Got it. The web playback sdk does use an iframe. Feel free to close this issue

**Comment by necropola** [comment]
Yeah, found it here ... 
![image](https://github.com/rain-fighters/AudioPick/assets/7461137/5d599985-da0b-4970-900e-2eea9eed4156)

What you could try is the following:

1. add `allow="microphone"` to your iframe.
2. Download the `0.3.10` source from github and set `"all_frames": true` for both the `main.js` and the `content.js` script in `manifest.json` .
3. install the modified extension in developer mode.

I have disabled injecting into sub-frames in version `0.3.10`, since it is rather unlikely that you''ll find `allow="microphone"` added to iframe permissions "in the wild", but that would be required to allow AudioPick to access the AudioDevice List and SetSinkId in the sub-frame.

Woudl still be interesting to see, whether this fixes your issue.

**Comment by fastnlight0** [comment]
Here's what I'm getting in the logs
```console
APV3-content.js (top-origin: https://spotify.sinno.link) | onMessage: getActiveDevice | sendResponse: default
content.js:17 APV3-content.js (top-origin: https://spotify.sinno.link) | onMessage: setActiveDevice | sendAudioDevice: BlackHole 2ch (Virtual)
content.js:17 APV3-content.js (sub-origin: https://sdk.scdn.co) | onMessage: setActiveDevice | sendAudioDevice: BlackHole 2ch (Virtual)
content.js:17 APV3-content.js (top-origin: https://spotify.sinno.link) | setAudioDevice: BlackHole 2ch (Virtual) | micPolicy.state: granted
content.js:17 APV3-content.js (sub-origin: https://sdk.scdn.co) | setAudioDevice: BlackHole 2ch (Virtual) | micPolicy.state: denied
content.js:17 APV3-content.js (top-origin: https://spotify.sinno.link) | injectSink: d587107347ea88c466f149c7788f356a2e656fa5f2c22b693cb48e0c6230d8bf | micPolicy.state: granted
content.js:17 APV3-content.js (top-origin: https://spotify.sinno.link) | onMessage: getActiveDevice | sendResponse: BlackHole 2ch (Virtual)
```
I have manually granted mic permissions to sdk.scdn.co, but it's saying that they're denied. Do you have a potential solution?

By the way, here's the iframe:
```html
<iframe src="https://sdk.scdn.co/embedded/index.html" alt="Audio Playback Container" tabindex="-1" allow="encrypted-media; autoplay; microphone" style="position: absolute !important; left: -1px !important; width: 0px !important; height: 0px !important; border: none !important; outline: none !important;"></iframe>
```
It's added by Spotify, so I have some code to add the microphone to the allow list.

**Comment by necropola** [comment]
Hmm,  the logs look as if  `microphone` has not been added to the allow list, or rather has been added too late? You wrote that you have some code adding it. Does it maybe add it after the page embedding the iFrame has alaready been loaded? 

Have you tried a static HTML document with an iframe like the one above or rather what would I neeed to add to my example page to reproduce your scenario? Just adding the iframe just produces a blank rectangle, but microphoen access is granted to the iframe without explicitely granting it to the sub-frame domain, i. e. it's kinda "inherited" from the main window.  

```
content.js:17 APV3-content.js (sub-origin: https://sdk.scdn.co) | init: addListener(onMessage)
content.js:17 APV3-content.js (sub-origin: https://sdk.scdn.co) | setAudioDevice: Speakers (Scream (WDM)) | micPolicy.state: granted
content.js:17 APV3-content.js (sub-origin: https://sdk.scdn.co) | injectSink: 8a577d7beb29d2f1b8e7128d81ba3b5545ca6b9d2bfd9672708e7eb9487c68c5 | micPolicy.state: granted
```

**Comment by fastnlight0** [comment]
I put a console log statement, and the microphone seems to be added before the debug logs appear. Have you tried with the actual Spotify web playback sdk, or are you using a mock iframe?

**Comment by necropola** [comment]
I have just added this iframe to a static html document
```
<h3>Spotify SDK player in iframe</h3>
<iframe src="https://sdk.scdn.co/embedded/index.html"
     alt="Audio Playback Container" tabindex="-1"
     allow="encrypted-media; autoplay; microphone"
     style="">
</iframe>
```
I understand that such an iframe is added dynamically by the spotify SDK and you are adding `microphone` to the allow list afterwards and probably too late, i. e. after the ifarme has beeen already loaded by the browser.

**Comment by fastnlight0** [comment]
My website's main page is the same file as the login page. You should be able to see the code without logging in. If you want, I can publish my website's source and you can host it yourself

**Comment by necropola** [comment]
It feels like you are tearing my arm off ... sorry.

**Comment by rafikDev** [comment]
I saw this was just closed :( 

I followed this thread yesterday since I have the same issue, I would love to use Audiopick with a tab that hosts a spotify SDK player. I can't offer much expertise to the conversation, but will offer a donation if you would consider that helpful. But I respect if you're done with this.

For what it's worth, my app (currently only on localhost) first connects to the spotify sdk, which then creates the iframe. If the modified dev build of audiopick you suggested is not activated, I am able to edit the permission for the microphone (as @fastnlight0 ) with 

```
const spotifyIframe = document.querySelector('iframe[src="https://sdk.scdn.co/embedded/index.html"]');
      console.log('Modify the iframe', spotifyIframe)
      if (spotifyIframe) {
        spotifyIframe.setAttribute('allow', 'encrypted-media; autoplay; microphone');
      }
```

which gives me this iframe element in chrome
`<iframe src="https://sdk.scdn.co/embedded/index.html" alt="Audio Playback Container" tabindex="-1" allow="encrypted-media; autoplay; microphone" style="position: absolute !important; left: -1px !important; width: 0px !important; height: 0px !important; border: none !important; outline: none !important;"></iframe>`

If your suggested dev build is activated, 'spotifyIframe' returns null and I somehow get three iframe elements:
```
<iframe src="https://sdk.scdn.co/embedded/index.html" alt="Audio Playback Container" tabindex="-1" allow="encrypted-media; autoplay" style="position: absolute !important; left: -1px !important; width: 0px !important; height: 0px !important; border: none !important; outline: none !important;"></iframe>
<iframe src="https://sdk.scdn.co/embedded/index.html" alt="Audio Playback Container" tabindex="-1" allow="encrypted-media; autoplay" style="position: absolute !important; left: -1px !important; width: 0px !important; height: 0px !important; border: none !important; outline: none !important;"></iframe>
<iframe id="webpack-dev-server-client-overlay" src="about:blank" style="position: fixed; inset: 0px; width: 100vw; height: 100vh; border: none; z-index: 2147483647;"></iframe>
```

Next, the player is created, which returns an error if Audiopick is enabled, so the player is not created

```
const player = new window.Spotify.Player({
        name: `Deck ${deck}`,
        getOAuthToken: async (cb) => {
            const newToken = await fetchNewTokenForDeck(deck);
            if (newToken) {
                cb(newToken);
            } else {
                console.error(`Failed to fetch a new token for deck ${deck}`);
            }
        },
        volume: 1,
        enableMediaSession: true
    });
```


The error is 
`SpotifyPlayer.js:206 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Player')`

Audiopick logs:
```
APV3-content.js (top-origin: https://localhost:3000) | init: addListener(onMessage)
content.js:17 APV3-content.js (top-origin: https://localhost:3000) | setAudioDevice: default | micPolicy.state: prompt
content.js:17 APV3-content.js (top-origin: https://localhost:3000) | injectSink: default | micPolicy.state: prompt
content.js:17 APV3-content.js (top-origin: https://localhost:3000) | onMessage: getActiveDevice | sendResponse: default
content.js:17 APV3-content.js (top-origin: https://localhost:3000) | onMessage: getActiveDevice | sendResponse: default
 APV3-content.js (sub-origin: https://sdk.scdn.co) | init: addListener(onMessage)
content.js:17 APV3-content.js (sub-origin: https://sdk.scdn.co) | init: addListener(onMessage)
 APV3-content.js (sub-origin: https://sdk.scdn.co) | setAudioDevice: default | micPolicy.state: denied
content.js:17 APV3-content.js (sub-origin: https://sdk.scdn.co) | setAudioDevice: default | micPolicy.state: denied
```

Again - zero expectations here. Just taking my only shot and I'm willing to support if that's appropriate :)

Best regards.

**Comment by fastnlight0** [comment]
I got it to work! You need to allow all frames in the manifest, then, on the page, you must have this code:
```js
function findSpotifyIframe() {
    const iframes = document.getElementsByTagName('iframe');
    for (let i = 0; i < iframes.length; i++) {
        const iframe = iframes[i];
        if (iframe.src === 'https://sdk.scdn.co/embedded/index.html') {
            return iframe;
        }
    }
    return null;
}

function addMicrophoneToAllowList(iframe) {
    iframe.setAttribute('allow', 'encrypted-media; autoplay; microphone;');
    iframe.src = iframe.src;
    console.log('Microphone added to allow list for Spotify iframe');
}

const observer = new MutationObserver((mutations) => {
    mutations.forEach((mutation) => {
        if (mutation.type === 'childList') {
            const iframe = findSpotifyIframe();
            if (iframe) {
                addMicrophoneToAllowList(iframe);
                observer.disconnect();
            }
        }
    });
});
```

**Comment by necropola** [comment]
... and it's exactly what I said: You need to reload the iframe after modifying the `allow` parameter
```
iframe.setAttribute('allow', 'encrypted-media; autoplay; microphone;');
iframe.src = iframe.src;
```
