### ISSUE TITLE
AudioPick, overnight is not seeing BlackHole audio drivers

### ISSUE THREAD

**Issue by jchin-ria** [rain-fighters/AudioPick#56]
AudioPick loses (not seeing) the BlackHole audio devices once the computer idles for a few hours (except for the one set as default system audio output).

This is the audio driver:
https://github.com/ExistentialAudio/BlackHole/releases

And we have the 2-ch, 16-ch and 64-ch versions installed.

Once we restart the Chrome browser, it is all there again.
But we have to do this every morning to get AudioPick to see them again.

**Comment by necropola** [comment]
I suspect that this is more an issue of the driver, OS and/or Chrome. If teh API does not (no longer) list the device, it can't be "picked".

I assume that sites which allow to select Audio output devices, e. g. the Teams and Discord Web Applications do not see the device either when this happens. Can you check this, please? If this is the case, then there is nothing AudioPick can do.

I also foudn this issue here: https://github.com/ExistentialAudio/BlackHole/issues/524

**Comment by jchin-ria** [comment]
The issue is only with Chrome tabs.  Other applications like OBS and Zoom continue to see the other BlackHole devices.   If I restart Chrome (not the MacBook), it all works again.

**Comment by necropola** [comment]
What I meant was try to use a Audio-Enabled Web Application in Chrome when the device disppears, e. g. https://discord.com, and see whether the device is shown in the web app or not. If not, then it's a Chrome/Driver/OS issue and nothing AudioPick can fix.

**Comment by jchin-ria** [comment]
OK thanks for the clarification, this must be a Chrome browser issue then since we can see the virtual audio drivers in other apps.  By the way, the VB-Cable (https://vb-audio.com/Cable/VirtualCables.htm) virtual audio driver never disappears from Chrome or AudioPick.

**Comment by jchin-ria** [comment]
Just a note, for other users who might be looking for a virtual audio driver ... I am now testing SoundDesk Virtual Device (https://www.loudlab-app.com/sounddesk-vd) as an alternative to BlackHole.
