### ISSUE TITLE
Invalid URL. Not HTTPS

### ISSUE THREAD

**Issue by patelkes** [rain-fighters/AudioPick#61]
Why this has been resticted to HTTPS sites only. Please allow on home running server (in house) which are HTTP only. I am running webserver at home and I wants to redirect web page audio to VB Audio Cable IN which in terms forward to VB Audio Cable out for audio AI processing..

**Comment by necropola** [comment]
The extension needs to grant **Microphone Access** to sites with audio sources it wants to manipulate.  This is a (rather weird, if you ask me) requirement of the underlying API. Due to the sensitive nature of this permission, I don't want to grant it to insecure (possibly hacked or misconfigured) sites on the internet. At least not in the official releases of this extension.

But since the extension is open source, you can donwload the source and apply the changes (to `manifest.json` and `popup.js`) yourself. Alternatively you could just use a proper (LetsEncrypt) SSL certificate on your home server. I'd choose the latter, since it also avoids the warning you get on pretty much any modern browser, whenever you connect to an insecure site.
