### ISSUE TITLE
Clear the microphone permission after the tab is closed / option to clear them

### ISSUE THREAD

**Issue by kinggreedy** [rain-fighters/AudioPick#8]
Hi,

I just checked the page chrome://settings/content/microphone and saw a lot of page being allowed to use my microphone by the extension. I'm a bit of worried they might pickup my microphone if I accidentally left them open, as I never allow those site to use my microphone.

**Comment by necropola** [comment]
Either allowing access to audio input or output is required for getUserMedia and setSinkId to work. In my opinion it's a rather stupid requirement of the underlying API, but I clearly stated this in the description.

Actually I was already thinking about some "cleanup" feature that removes permissions for sites that haven't been visited in a while. Permissions are automatically (re-)added as needed, i. e. when a visited site (or an embedded iframe) has an html audio/video element that my extension finds.

Anyway. Thanks for the suggestion. Always good to see that there are people who care what permissions they grant (or let their apps grant) on the internet.

**Comment by necropola** [comment]
The current idea is to add a **☑️ clear** option to the Popup/UI which -- when checked -- would call  `chrome.contentSettings.microphone.clear` on **Apply...**  to remove all permissions that the extension has acquired so far and then re-acquire only the permission that is immeditely needed for the active tab.

The content script would still re-acquire permissions for sites which have stored/starred preferred devices, but this would happen slightly delayed, i. e. the actual switch to the preferred device would come delayed or possibly not work at all.

Also note that the reduction in acquired permissions would not be as *spectacular* as it might seem on first glance, because
- we are (since version `0.3.8`) no longer storing a global preferred audio device (for the browser) and
- we are setting the permission back to **ask** whenever the **Default Device** is chosen for a tab/site (again).

But since it would be optional, I might actually add this in a future version. A `clearMicAccess()` function is already in `popup,js`. It's just not called at the moment.

**Comment by necropola** [comment]
Implemented in commit a9c598a.
Will be available as a ☑️ smart option in the upcoming `0.3.10` release.
